export interface IHttpError {
  success: boolean;
  code: HTTP_STATUS;
  message: string;
  fields?: string[];
}

export interface IErrorForm {
  key?: IErrors | string;
  message: string;
  extra?: unknown;
}

export enum HTTP_STATUS {
  SUCCESS = 200,
  CREATED = 201,
  ACCEPTED = 202,
  NO_CONTENT = 204,
  BAD_REQUEST = 400,
  UNAUTHORIZED = 401,
  FORBIDDEN = 403,
  NOT_FOUND = 404,
  TOO_MANY_REQUESTS = 429,
  INTERNAL_SERVER_ERROR = 500,
}

export enum IErrors {
  ACCESS_TOKEN_EXPIRED = 'ACCESS_TOKEN_EXPIRED',
  ACCESS_TOKEN_INVALID = 'ACCESS_TOKEN_INVALID',
  REFRESH_TOKEN_EXPIRED = 'REFRESH_TOKEN_EXPIRED',
  REFRESH_TOKEN_INVALID = 'REFRESH_TOKEN_INVALID',
  REFRESH_TOKEN_BLACKLIST = 'REFRESH_TOKEN_BLACKLIST',
  SIGNIN_REQUIRED = 'SIGNIN_REQUIRED',
  NEED_ASK_PERMISSION_PRIVACY = 'NEED_ASK_PERMISSION_PRIVACY',
  DISABLED_PRIVACY = 'DISABLED_PRIVACY',
  FORBIDDEN_ACCESS = 'FORBIDDEN_ACCESS',
  NOT_FOUND = 'NOT_FOUND',
  UNAUTHORIZED = 'UNAUTHORIZED',
  EXISTED = 'EXISTED',
  ALREADY_JOINED = 'ALREADY_JOINED',
  DUPLICATE_JOIN_REQUEST = 'DUPLICATE_JOIN_REQUEST',
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  MAX_ATTENDEE_LIMIT = 'MAX_ATTENDEE_LIMIT',
  HAS_PENDING_REQUEST_PRIVACY = 'HAS_PENDING_REQUEST_PRIVACY',
  DUPLICATE = 'DUPLICATE',
  NEED_REQUIRED_QUERY_FIELDS = 'NEED_REQUIRED_QUERY_FIELDS',
  MAX_RATE_LIMIT = 'MAX_RATE_LIMIT',
  MODULE_DISABLED = 'MODULE_DISABLED',
}

